output "id" {
  description = "Autogenerated ID of the User, encoded in base64"
  value       = twingate_user.this.id
}

output "type" {
  description = "Indicates the User's type"
  value       = twingate_user.this.type
}
