output "id" {
  description = "Autogenerated ID of the User, encoded in base64"
  value       = module.twingate_user.id
}

output "type" {
  description = "Indicates the User's type"
  value       = module.twingate_user.type
}
